### ISSUE TITLE
Бързо превключване на канали

### ISSUE THREAD

**Issue by hestan** [sasbass/plugin.video.mytv_bg#1]
Направи ми впечатление, че вече каналите от менюто "Телевизия на живо" имат още едно подменю където да се избере дали да тръгне "живия" стрийм или с отместване назад  във времето. Това прави бързото превключване от канал на канал много по-пипкаво, защото добавя още една стъпка.
Това промяна в АПИто ли е, защото при мен върви версия 2.0.0 и нямам спомен да беше така преди?
В неофициалния стар плъгин беше направено така, че или да влезе човек в листата с бъзр избор на канали, или с избор и на офсет.

**Comment by portokala123** [comment]
Да това е промяна в API-то. Тъй като API-то се ползва и за мобилните телефони и там настояваха да има вариянт за избор на отместването. До колкото разбирам на неофициялния е имало второ меню с отмествания? Тоес на живо списъка е бил само с наживо? 

По пирнцип сега като се замисля вариянтите са:

1. Два списъка: единия на живо и втори както е в момента.

2. Един списък, като отместването да се избира преди да се избере канал.  Този вариянт изглежда функционално най-добре, тъй като ще позволи да може да се превкючват и каналите с отместване.

Аз мога да имлементирам втория вариянт тестово и да го добавя в менюто, като оставя и текущия вариянт, за да видим как ще реягират потребителите.

**Comment by ipetrov87** [comment]
Аз личо нямам проблем с новото API за мен ще е добре ако "На живо" се преименува "На живо или с отместване". Логигата ми е следната колкото повече менюта толкова по сложно за крайния потребител да намери това което търси, повече натискания на бутона за избор, по отекчително за крайния потребител. Затова се придържам към мисленето KISS( keep it simple and short). Иначе ако се правят промени предпочитам първия вариянт.

**Comment by portokala123** [comment]
Добвени са двете опции на живо и с отместване в друго меню. За отместванията в крайна сметка се спрях на: първо се избира отместване след това телевизия с цел все пак ако някой има желание да гледа с отместване да може да по лесно да се преключват каналите. 

Сега оства да се добавят описания на това което се излъчва в момента по телевизиите, че иначе е доста неориентирано.
