### ISSUE TITLE
Съобщение за грешен емайл или парола при валиден акаунт

### ISSUE THREAD

**Issue by idenev** [sasbass/plugin.video.mytv_bg#2]
При въвеждане на логин информацията в неофициянлия стар плъгин всичко е наред и достъпа е на лице. В тази версия въвеждах десетки пъти същите данни и всеки път резултата е един и същ "Грешен Емайл или Парола, моля коригирайте ги и опитайте отново".

**Comment by portokala123** [comment]
Да имаше малка разлика, може ли да опитате сега дали вече не е оправен проблема.

**Comment by idenev** [comment]
Мерси. Всичко вече е наред.
